### ISSUE TITLE
Update to PagerDuty API v2

### ISSUE THREAD

**Issue by ofavre** [darkcrux/gopherduty#2]
Hi,

PagerDuty API v1 is being [decommissioned](https://v2.developer.pagerduty.com/docs/v1-rest-api-decommissioning-faq) and will no longer work after 2018/10/19.
The events must now be sent to `https://v2.developer.pagerduty.com/docs/send-an-event-events-api-v2`.

Any plans for an update?
Thanks!

**Comment by nh2** [comment]
@ofavre Are you sure `gopherduty` is using the API that is being decommissioned?

From what you linked:

> This change only affects the v1 REST API. You can continue to use the v1 Events API as you do today.

**Comment by ofavre** [comment]
Good catch, my bad.
The API you are using is not the one being decommissioned indeed.
